Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_url = "https://app.vagrantup.com/ubuntu/boxes/focal64"
  config.vm.hostname = "server"
  config.vm.provision "shell", path: "installMariaDB.sh"
  config.vm.network "private_network", ip: "192.168.50.4"
end
