Vagrant.configure("2") do |config|
  config.vm.box = "debian/contrib-buster64"
  config.vm.hostname = "testserver"
  config.vm.define "testserver"
  config.vm.box_url = "https://app.vagrantup.com/debian/boxes/contrib-buster64"
  config.vm.provision "shell", path: "installMariaDB.sh"
  config.vm.network "private_network", ip: "192.168.50.237"

end
